- .github/workflows/links.yml
- .gitignore
- .lycheeignore
- README.md
- content/shortcodes.md.stub
- content/training.md
> Use `Lychee` to check for broken links

- .pre-commit-config.yaml
- README.md
- content/contact.md
> Add `pre-commit` support

- README.md
- netlify.toml
> Netlify deployment infrastructure

- content/news/2020/09/battery-modelling-webinar-series.md
- content/news/2020/11/faraday-institution-conference.md
- content/news/2020/12/pybamm-0.3.0.md
- content/news/2021/03/oxford-battery-modelling-symposium.md
- content/news/2021/03/pybamm-0.4.0.md
- content/news/2021/06/jors-paper.md
- content/news/2021/07/battery-modelling-webinar-series.md
- content/news/new-theme.md
Closes #9 
Pages are now in Markdown format and are sorted in order of publishing via folders and subfolders (year, month). All pages include YAML front matter for post metadata
> Add news pages from PyBaMM blogspot

- assets/css/overrides.css
- config.yaml
- netlify.toml
Mostly taken from the results for https://pybamm.org on these websites:
1. https://www.accessibilitychecker.org/audit/?website=pybamm.org&flag=ww
2. https://fae.disability.illinois.edu/pages/1892fbc904f7f899/rc/all/page/1/
3. https://www.tawdis.net/
4. Browser extension available at https://www.tpgi.com/arc-platform/arc-toolkit/
5. https://pybamm.org/reports/lighthouse.html (Netlify)
Cannot be fixed without changes in the theme itself:
1. Landmark regions and page relationships
2. Tab-focusable aria-labels for navbar dropdown (aria-hidden dropdowns cannot be focused)
3. Bypass blocks
4. Purposes and states for links
Fixed in this PR:
1. All home screen elements have a minimum font size of 16 pixels
2. Changes to the layout (hero and logo positions) for mobile devices
3. Smooth animations …
> Accessibility improvements

- content/about/index.md
@martinjrobins is this the correct web page for you? Feel free to edit directly if not
> add Martin to steering committee

- content/gsoc/2021/index.md
- content/gsoc/2022/index.md
- content/gsoc/2023/_index.md
- content/gsoc/2024/_index.md
- GSoC 2024 project ideas list page
- Blank project with headings
> Add GSoC 2024 project ideas page

- content/teams.md
- scripts/generate_teams.py
- static/teams/contributors.html
- static/teams/emeritus-maintainers.html
- static/teams/maintainers.html
Fixes #62 
This PR will solve this issue
I have tested it in a separate project and it returned the data
> Change the github API to the `.all-contributorsrc` file

- content/gsoc/2024/_index.md
cc: @tinosulzer
also cc: @Saransh-cpp @arjxn-py
Please let me know if we should update the mentioned stretch goal too here or let the candidate(s) do so in their proposal?
> Update `pytest`-migration project duration

- content/404.md
- content/GOVERNANCE.md
- content/_index.md
- content/about/index.md
- content/community.md
- content/contribute.md
- content/gsoc/2021/index.md
- content/gsoc/2022/index.md
- content/gsoc/2023/_index.md
- content/gsoc/_index.md
- content/learn.md
- content/open-source-programs.md
- content/publications.md
- content/roadmap.md
- content/teams.md
- content/training.md
> Added summaries

- .github/workflows/teams.yml
- content/gsoc/2021/index.md
- content/gsoc/2022/index.md
- content/gsoc/2023/_index.md
- static/teams/contributors.html
- static/teams/maintainers.html
- teams/MAINTAINERS
Just a minor update with valid working URLs
> Fix broken links

- content/community.md
- content/contribute.md
I have added some additional details on how to contact us, including some etiquette. I have also updated the email from pybamm@gmail.com to pybamm@pybamm.org.
> Update contact details

- content/jobs-t-and-c.md
- content/jobs.md
Link to the payment portal has now been updated. Some minor tweaks in the section on how to post a job (and copied that part to the main jobs page too).
> Update payment link

- config.yaml
- content/telemetry.md
Added telemetry page so the information is not just in the release notes. I have basically copied the information across.
> Add telemetry page

- config.yaml
- content/news/2020/11/24/faraday-institution-conference.md
- content/training.md
- netlify.toml
- https://github.com/scientific-python/scientific-python-hugo-theme/releases/tag/v0.21
- https://github.com/gohugoio/hugo/releases/tag/v0.140.2
> Bump to SPHT v0.21, and update Python and Hugo

- content/about/index.md
- content/community.md
- content/learn.md
- content/news/2025/01/15/pybamm-25.1.md
Added release notes for PyBaMM 25.1
> Release notes 25.1

- content/gsoc/2025/_index.md
- content/gsoc/_index.md
Created a placeholder page for GSoC 2025 so team members can open PRs with project proposals.
> Placeholder GSoC 2025

- .github/workflows/links.yml
- content/gsoc/2024/_index.md
- content/gsoc/2025/_index.md
This PR adds the first project for GSoC 2025 – not finalised yet, opening this PR for discussion.
> GSoC 2025 project idea: type hints for PyBaMM models

- assets/css/overrides.css
See https://github.com/scientific-python/scientific-python-hugo-theme/issues/664 and https://github.com/scientific-python/scientific-python-hugo-theme/issues/641. To be dropped after it's fixed upstream.
> Fix navbar overlay

- .gitpod.yml
Automatically install sass in gitPod.
> patch: install dart sass

- content/gsoc/2025/_index.md
Please feel free to uncomment your name in the list of potential mentors :)
> List `Adding type hints to PyBaMM models` Project again

- .pre-commit-config.yaml
- content/news/2025/04/02/pybamm-25.4.md
Here are the release notes for v25.4. I am away next week, so please feel free to edit and merge.
> Release notes 25.4

- content/gsoc/2025/_index.md
I realised that I would be reviewing PRs anyways, so might as well be added here. Would be happy to review PRs and participate in the meetings ✅ (however, won't be able to lead any meetings).
> Update GSoC project

- content/GOVERNANCE.md
As discussed in the March SC meeting.
Last work as an SC member 🫡
> Update tenure docs for SC members
